# Generated by Django 3.2.3 on 2021-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drugIngrediant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField(default='0')),
                ('d_id', models.IntegerField(default='0')),
                ('amount', models.FloatField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='ingrediantList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField(default='0')),
                ('location', models.IntegerField(default='0')),
                ('required', models.CharField(default='F', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='mixedDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField(default='0')),
                ('d_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usrCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(default='0')),
                ('u_name', models.CharField(default='', max_length=20)),
                ('u_pwd', models.TextField(default='')),
            ],
        ),
    ]
