# Generated by Django 3.2.3 on 2021-05-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientnav', '0003_drugingrediant_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediantlist',
            name='concentration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
